---
version: "2.1"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/pi/docker/heimdall:/config
    ports:
      - 8080:80
      - 44344:443
    restart: unless-stopped
