---
version: "2.1"

volumes:
  heimdall_data:

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - heimdall_data:/config:ro
    ports:
      - 8008:80
      - 44344:443
    restart: unless-stopped
