---
version: "2.1"

volumes:
  guacamole_data:

services:
  guacamole:
    image: oznu/guacamole:armhf
    container_name: guacamole
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - guacamole_data:/config:ro
    ports:
      - 50545:8080
    restart: unless-stopped
