---
version: "2.1"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - /home/pi/docker/config/jellyfin:/config
      - /home/pi/downloads/tvshows:/data/tvshows
      - /home/pi/downloads/movies:/data/movies
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      - 8096:8096
    restart: unless-stopped
