---
version: "2.1"

volumes:
  sonarr_data:

  radarr_data:

  jackett_data:

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - sonarr_data:/config:ro
      - /home/pi/downloads/tvshows:/tv
      - /home/pi/downloads/Torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - radarr_data:/config:ro
      - /home/pi/downloads/movies:/movies
      - /home/pi/downloads/Torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - AUTO_UPDATE=true
    volumes:
      - jackett_data:/config:ro
      - /home/pi/downloads/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
