---
version: "3"

services:
  dashy:
    image: lissy93/dashy
    container_name: dashy
    volumes:
      - /etc/dashy/conf.yml:/app/public/conf.yml
      - /etc/dashy/item-icons:/app/public/item-icons
    ports:
      - 8085:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
